var types = [
	{name:"base", display:"base coat", category:"polish"},
	{name:"chrome", display:"chrome", category:"polish"},
	{name:"crackle", display:"crackle", category:"polish"},
	{name:"crelly", display:"crelly", category:"polish"},
	{name:"creme", display:"creme", category:"polish"},
	{name:"dip", display:"dip", category:"polish"},
	{name:"duochrome", display:"duochrome", category:"polish"},
	{name:"flakie", display:"flakie", category:"polish"},
	{name:"frost", display:"frost", category:"polish"},
	{name:"gel", display:"gel", category:"polish"},
	{name:"glitter", display:"glitter", category:"polish"},
	{name:"glow", display:"glow", category:"polish"},
	{name:"glue", display:"glue", category:"tool"},
	{name:"holo", display:"holo", category:"polish"},
	{name:"jelly", display:"jelly", category:"polish"},
	{name:"latex", display:"latex", category:"tool"},
	{name:"magnetic", display:"magnetic", category:"polish"},
	{name:"matte", display:"matte", category:"polish"},
	{name:"metallic", display:"metallic", category:"polish"},
	{name:"multichrome", display:"multichrome", category:"polish"},
	{name:"neon", display:"neon", category:"polish"},
	{name:"oil", display:"oil", category:"tool"},
	{name:"pearl", display:"pearl", category:"polish"},
	{name:"pen", display:"pen", category:"polish"},
	{name:"plate", display:"stamping plate", category:"tool"},
    {name:"powder", display:"powder", category:"polish"},
	{name:"scented", display:"scented", category:"polish"},
	{name:"sheer", display:"sheer", category:"polish"},
	{name:"shimmer", display:"shimmer", category:"polish"},
	{name:"striper", display:"striper", category:"polish"},
	{name:"suede", display:"suede", category:"polish"},
	{name:"texture", display:"texture", category:"polish"},
	{name:"thermal", display:"thermal", category:"polish"},
	{name:"top", display:"top coat", category:"polish"},
	{name:"uv", display:"uv", category:"polish"},
	{name:"vinyl", display:"vinyl", category:"tool"}
];


module.exports = types;